development: &default
  adapter: postgresql
  encoding: unicode
  database: alerting
  pool: 5
  username: db
  password: db
  host: db


test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

